// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNr8BMI_fpZLUtw9SvyiErh4ITJTD5ME0',
    appId: '1:287829578766:web:46c8d120ed4a7775f4d85f',
    messagingSenderId: '287829578766',
    projectId: 'fir-chat-b21e3',
    authDomain: 'fir-chat-b21e3.firebaseapp.com',
    storageBucket: 'fir-chat-b21e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZao3qC90ebZWNF8UgeSho_PiI_aJ8BNM',
    appId: '1:287829578766:android:506754cd658c0e94f4d85f',
    messagingSenderId: '287829578766',
    projectId: 'fir-chat-b21e3',
    storageBucket: 'fir-chat-b21e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApyV73XdVtZiDw-asg9d79UHQ_X-ksmsE',
    appId: '1:287829578766:ios:cb39661e1e60f7daf4d85f',
    messagingSenderId: '287829578766',
    projectId: 'fir-chat-b21e3',
    storageBucket: 'fir-chat-b21e3.appspot.com',
    iosClientId: '287829578766-monnf25t97272avpeloj4irqc5ksa00h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApyV73XdVtZiDw-asg9d79UHQ_X-ksmsE',
    appId: '1:287829578766:ios:cb39661e1e60f7daf4d85f',
    messagingSenderId: '287829578766',
    projectId: 'fir-chat-b21e3',
    storageBucket: 'fir-chat-b21e3.appspot.com',
    iosClientId: '287829578766-monnf25t97272avpeloj4irqc5ksa00h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );
}
